apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "fourthone"
  description: "fourthone example description"
  annotations:
    github.com/project-slug: "inf-backstage/fourthone"
    backstage.io/techdocs-ref: github:https://github.com/inf-backstage/fourthone
spec:
  type: service
  lifecycle: experimental
  owner: "venkataru"
